# Generated by Django 4.2.2 on 2024-02-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_user_bio_user_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
